#pragma once

enum e_ENEMY_KIND
{
	ENEMY_KIND_0000_SNAIL_GREEN		= 1,
	ENEMY_KIND_0000_SNAIL_BLUE		= 2,
	ENEMY_KIND_0000_SNAIL_RED		= 3,

	ENEMY_KIND_NONE = 0
};

enum e_BOSS_KIND
{
	BOSS_KIND_0000_KING_SLIME		= 1,

	BOSS_KIND_NONE = 0
};